import Fire from "../../../../assets/animations/Fire.json";
import HauntedSkull from "../../../../assets/animations/HauntedSkull.json";
import RunningCircle from "../../../../assets/animations/RunningCircle.json";

export default [
  {
    key: "repair_costs",
    emoji: "🔧",
    title: "Gastos Imprevistos",
    desc: "Reparaciones urgentes devoran tus reservas de oro.",
    animation: Fire,
  },
  {
    key: "delayed_permit",
    emoji: "📄",
    title: "Permiso Atrasado",
    desc: "Los escribas reales extraviaron tu solicitud. El proyecto se detiene.",
    animation: RunningCircle,
  },
  {
    key: "market_dip",
    emoji: "📉",
    title: "Bajada de Mercado",
    desc: "El valor de tus propiedades cae como una torre de cartas encantadas.",
    animation: HauntedSkull,
  },
  {
    key: "tenant_trouble",
    emoji: "😠",
    title: "Inquilino Problemático",
    desc: "Los inquilinos desaparecen dejando deudas y murciélagos.",
    animation: HauntedSkull,
  },
  {
    key: "magic_failure",
    emoji: "💥",
    title: "Hechizo Fallido",
    desc: "El conjuro de mantenimiento se revierte. Todo se cubre de limo arcano.",
    animation: Fire,
  },
  {
    key: "tax_increase",
    emoji: "💰",
    title: "Impuesto del Reino",
    desc: "El rey decreta un tributo extra para financiar su nuevo castillo.",
    animation: RunningCircle,
  },
  {
    key: "storm_damage",
    emoji: "🌪️",
    title: "Tormenta Mágica",
    desc: "Un rayo encantado derrite los techos de tus propiedades.",
    animation: Fire,
  },
  {
    key: "fraudulent_broker",
    emoji: "🕵️",
    title: "Corredor Falso",
    desc: "Un goblin disfrazado desaparece con tu adelanto.",
    animation: HauntedSkull,
  },
  {
    key: "golem_strike",
    emoji: "⚙️",
    title: "Huelga de Golems",
    desc: "Los obreros mecánicos exigen almas nuevas como pago. Construcción paralizada.",
    animation: RunningCircle,
  },
  {
    key: "tenant_curse",
    emoji: "🧙‍♂️",
    title: "Maldición del Inquilino",
    desc: "Un mago despechado lanza un hechizo de humedad infinita en tu propiedad.",
    animation: HauntedSkull,
  },
  {
    key: "permit_denied",
    emoji: "🚫",
    title: "Permiso Denegado",
    desc: "El consejo urbanístico enano declara tu plano ‘anticuado’.",
    animation: RunningCircle,
  },
  {
    key: "fire_accident",
    emoji: "🔥",
    title: "Incendio Arcano",
    desc: "Una vela rúnica inicia un incendio que ni el gremio de magos pudo apagar.",
    animation: Fire,
  },
  {
    key: "bad_investment",
    emoji: "🐍",
    title: "Inversión Serpenteante",
    desc: "El terreno ‘prometedor’ resultó ser una ciénaga con ilusiones de prosperidad.",
    animation: HauntedSkull,
  },
  {
    key: "theft_event",
    emoji: "🦹",
    title: "Robo de Tesoro",
    desc: "Bandidos nocturnos se llevan la caja de alquileres mensuales.",
    animation: HauntedSkull,
  },
  {
    key: "bureaucratic_maze",
    emoji: "🏛️",
    title: "Laberinto Burocrático",
    desc: "Cada sello requiere otro sello. Tu paciencia y tu oro se evaporan.",
    animation: RunningCircle,
  },
  {
    key: "plague_event",
    emoji: "🦠",
    title: "Plaga de Moho Arcano",
    desc: "Los muros comienzan a respirar y a quejarse. Los inquilinos huyen.",
    animation: Fire,
  },
  {
    key: "loan_trouble",
    emoji: "📉",
    title: "Deuda Incontrolable",
    desc: "El mago financiero cambia las reglas del contrato y duplica los intereses.",
    animation: HauntedSkull,
  },
  {
    key: "rune_glitch",
    emoji: "🔮",
    title: "Desfase Rúnico",
    desc: "Las runas de seguridad se invierten y ahora expulsan a los inquilinos.",
    animation: RunningCircle,
  },
  {
    key: "pirate_raid",
    emoji: "🏴‍☠️",
    title: "Saqueo Pirata",
    desc: "Los corsarios del puerto fantasma confunden tu propiedad con un depósito de botín.",
    animation: Fire,
  },
  {
    key: "ghost_infestation",
    emoji: "👻",
    title: "Infestación Espectral",
    desc: "Los nuevos residentes no están vivos y tampoco pagan renta.",
    animation: HauntedSkull,
  },
];
