import PiggyBank from "../../../../assets/animations/PiggyBank.json";
import DogMoney from "../../../../assets/animations/DogMoney.json";
import NotificationBell from "../../../../assets/animations/NotificationBell.json";
import DogEating from "../../../../assets/animations/DogEating.json";

export default [
  {
    key: "gain_rent",
    emoji: "💎",
    title: "Plusvalía",
    desc: "Tu inversión gana valor sostenidamente. El oráculo sonríe ante tu previsión.",
    animation: PiggyBank,
  },
  {
    key: "good_tenant",
    emoji: "🧾",
    title: "Inquilino Ideal",
    desc: "Pagos puntuales y ni una queja del vecindario mágico.",
    animation: NotificationBell,
  },
  {
    key: "smooth_sale",
    emoji: "🏠",
    title: "Venta Ágil",
    desc: "Cierras una operación con excelente retorno y sin intervención de demonios notariales.",
    animation: DogMoney,
  },
  {
    key: "guild_recognition",
    emoji: "🏅",
    title: "Reconocimiento del Gremio",
    desc: "El consejo inmobiliario de enanos te nombra ‘Inversor del Año’.",
    animation: NotificationBell,
  },
  {
    key: "tenant_festival",
    emoji: "🎉",
    title: "Festival de Inquilinos Felices",
    desc: "Tu propiedad atrae a inquilinos alegres que celebran su estancia con pociones y música.",
    animation: DogEating,
  },
  {
    key: "eco_award",
    emoji: "🌿",
    title: "Premio Verde del Reino",
    desc: "Tu edificio sustentable gana el favor de los druidas locales.",
    animation: PiggyBank,
  },
  {
    key: "quick_flip",
    emoji: "⚡",
    title: "Venta Relámpago",
    desc: "Revendes tu propiedad en tiempo récord con una ganancia digna de un mago financiero.",
    animation: DogMoney,
  },
  {
    key: "good_alliance",
    emoji: "🤝",
    title: "Alianza Estratégica",
    desc: "Te asocias con un gremio confiable que impulsa tus proyectos a nuevas alturas.",
    animation: NotificationBell,
  },
  {
    key: "lucky_spell",
    emoji: "✨",
    title: "Hechizo de Fortuna",
    desc: "Una bendición arcana duplica tus ingresos de alquiler por pura suerte cósmica.",
    animation: PiggyBank,
  },
  {
    key: "tax_blessing",
    emoji: "📜",
    title: "Exención Real",
    desc: "El rey te concede beneficios fiscales por tu contribución al desarrollo urbano.",
    animation: DogMoney,
  },
  {
    key: "stable_market",
    emoji: "🏗️",
    title: "Mercado Estable",
    desc: "Los precios se mantienen firmes y tus propiedades prosperan sin esfuerzo extra.",
    animation: PiggyBank,
  },
  {
    key: "great_review",
    emoji: "⭐",
    title: "Cinco Runas Doradas",
    desc: "Tus huéspedes dejan críticas estelares en el portal de alquiler mágico.",
    animation: NotificationBell,
  },
  {
    key: "tenant_loyalty",
    emoji: "💌",
    title: "Contrato Renovado",
    desc: "Tu inquilino firma por tres años más y te regala una poción de gratitud.",
    animation: NotificationBell,
  },
  {
    key: "magic_renovation",
    emoji: "🔮",
    title: "Reforma Encantada",
    desc: "Un conjuro de eficiencia mejora toda tu propiedad sin gastar una moneda.",
    animation: DogEating,
  },
  {
    key: "property_award",
    emoji: "🏆",
    title: "Premio al Mejor Desarrollo",
    desc: "Tu condominio de cristal lunar recibe el reconocimiento del consejo arquitectónico.",
    animation: PiggyBank,
  },
  {
    key: "market_vision",
    emoji: "🧭",
    title: "Visión de Mercado",
    desc: "Predijiste correctamente la expansión urbana gracias a tu bola de cristal inmobiliaria.",
    animation: NotificationBell,
  },
  {
    key: "tenant_referral",
    emoji: "🪄",
    title: "Recomendación Mágica",
    desc: "Tus propios inquilinos traen nuevos arrendatarios de confianza.",
    animation: DogEating,
  },
  {
    key: "wise_investment",
    emoji: "📈",
    title: "Inversión Sabia",
    desc: "Tu paciencia fue recompensada. El terreno se revalorizó más de lo previsto.",
    animation: PiggyBank,
  },
  {
    key: "hero_tenant",
    emoji: "🦸",
    title: "Inquilino Legendario",
    desc: "Un héroe famoso alquila tu propiedad y la convierte en sitio turístico.",
    animation: DogMoney,
  },
  {
    key: "banquet_profit",
    emoji: "🍗",
    title: "Banquete de Ganancias",
    desc: "Brindas por tus rendimientos con vino élfico y pastel de rentabilidad.",
    animation: DogEating,
  },
];
