export default [
  { key: "slime", name: "Slime de Inflación", emoji: "🟢", hp: 1, attack: 1 },
  { key: "rat", name: "Rata de Gastos", emoji: "🐀", hp: 1, attack: 1 },
  { key: "imp", name: "Duende de Tasas", emoji: "👺", hp: 2, attack: 1 },
  {
    key: "goblin",
    name: "Goblin de Burocracia",
    emoji: "🟡",
    hp: 2,
    attack: 2,
  },
  {
    key: "skeleton",
    name: "Esqueleto de Deuda",
    emoji: "💀",
    hp: 2,
    attack: 2,
  },
  {
    key: "wraith",
    name: "Espectro de Vacancia",
    emoji: "👻",
    hp: 3,
    attack: 2,
  },
  { key: "orc", name: "Orco de Impuestos", emoji: "🟡", hp: 3, attack: 3 },
  { key: "drake", name: "Draco de Tasa Alta", emoji: "🐉", hp: 4, attack: 3 },
  {
    key: "golem",
    name: "Gólem de Regulación",
    emoji: "🗿",
    hp: 5,
    attack: 2,
  },
  {
    key: "mage",
    name: "Mago de la Inflación",
    emoji: "🧙",
    hp: 5,
    attack: 4,
  },
  { key: "hydra", name: "Hidra de Costos", emoji: "🐉", hp: 6, attack: 4 },
  { key: "demon", name: "Demonio de Recesión", emoji: "👹", hp: 7, attack: 5 },
];
